# This is a basic workflow to help you get started with Actions

name: release u-boot
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          export UBootSrcRepo=$(echo $GITHUB_REPOSITORY | cut -d/ -f1)
          chmod a+x ./build-uboot.sh
          ./build-uboot.sh

      - name: Release
        #uses: softprops/action-gh-release@v2
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 #temporarily broken
        with:
          files: |
            u-boot-r36s.bin
            u-boot-r36s.tar
          draft: true
